  - block: #======For Debian ========#
      - name: apt update
        apt: update_cache=yes

      - name: Install mail server packages
        apt:
          name: "{{ packages }}"
        vars:
          packages:
            - apache2
            - postfix
            - dovecot-core
            - dovecot-imapd
            - dovecot-pop3d
            - spamassassin
            - php7.2

      - name: install mysql-server for Debian
        apt: name=mysql-server state=latest update_cache=yes
        notify: mysql start

      - lineinfile:
          path: /etc/dovecot/conf.d/10-mail.conf
          regexp: '^mail_location = mbox:~/mail:INBOX=/var/mail/%u'
          insertafter: '^#   mail_location = maildir:~/Maildir'
          line: 'mail_location = maildir:~/Maildir'
        notify: dovecot restart

      - template:
          src: /etc/ansible/roles/mailserver/files/ubuntu/main.cf.j2
          dest: /etc/postfix/main.cf.ansible

      - name: Download roundcube
        get_url: 
          url: https://github.com/roundcube/roundcubemail/releases/download/1.3.8/roundcubemail-1.3.8-complete.tar.gz
          dest: /tmp/
          mode: 0440

      - name: Creates directory /var/www/html/rc
        file:
          path: /var/www/html/rc
          state: directory
          mode: 0775

      - name: Extract roundcube.tar.gz into /var/www/html/rc
        unarchive:
          src: /tmp/roundcubemail-1.3.8-complete.tar.gz
          dest: /tmp/

      - name: rename roundcube directory
        command: mv /tmp/roundcubemail-1.3.8 /tmp/rc

      - name: Move roundcube to /var/www/html
        command: mv /tmp/rc/ /var/www/html/

      - name: service apache2 reload
        service:
          name: apache2
          state: reloaded
    when: ansible_os_family == "Debian"
